# Generated by Django 5.0.6 on 2024-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_pfp/default_pfp.png', upload_to='profile_pictures/'),
        ),
    ]
